package br.com.fiap.postech.carworkshop.architecture;

import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import com.tngtech.archunit.core.importer.ImportOption;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;
import static com.tngtech.archunit.library.freeze.FreezingArchRule.freeze;

/**
 * Architecture enforcement: trava as regras da Clean Architecture.
 *
 * <p>Every module has since been cleaned, so the dependency violations frozen earlier are now
 * <em>burned</em> and these rules become <strong>strict</strong>: domain stays framework-free, the
 * use case layer no longer reaches into {@code infrastructure} (V2), and the {@code workorder}
 * gateways no longer touch other modules' infrastructure (V3). A regression breaks the build.</p>
 *
 * <p>The one exception is <strong>V1</strong> ({@code usecase -> adapter}: interactors still build
 * adapter DTOs/presenters). V1 is the <em>optional</em> Refinement of the DoD and was deliberately
 * deferred, so its rule stays wrapped in {@link
 * com.tngtech.archunit.library.freeze.FreezingArchRule#freeze}: the violations that exist today are
 * recorded in {@code archunit_store/} and a <strong>new</strong> {@code usecase -> adapter}
 * dependency (outside the frozen set) still breaks the build. Do not edit {@code archunit_store/} by
 * hand — it is regenerated by the build.</p>
 *
 * <p>Plain JUnit 5 {@code @Test} methods (not the ArchUnit JUnit engine) so Surefire counts them and
 * fails the build on a new violation. Only production classes are analysed
 * ({@link ImportOption.DoNotIncludeTests}).</p>
 */
class ArchitectureTest {

    private static JavaClasses productionClasses;

    @BeforeAll
    static void importProductionClasses() {
        productionClasses = new ClassFileImporter()
                .withImportOption(new ImportOption.DoNotIncludeTests())
                .importPackages("br.com.fiap.postech.carworkshop");
    }

    /**
     * Domain stays framework-free (D4 — Clean Architecture "à risca": core in plain Java).
     * No {@code jakarta.*}, {@code io.quarkus.*} or {@code org.hibernate.*} in the domain layer.
     * Lombok is compile-time only, so it leaves no runtime dependency here.
     */
    @Test
    void domain_is_framework_free() {
        noClasses()
                .that().resideInAPackage("..domain..")
                .should().dependOnClassesThat().resideInAnyPackage(
                        "jakarta..", "io.quarkus..", "org.hibernate..")
                .as("domain must not depend on jakarta.*, io.quarkus.* or org.hibernate.*")
                .check(productionClasses);
    }

    /**
     * STRICT (V2): the use case layer must not reach into {@code infrastructure}.
     * No freeze — any new {@code usecase -> infrastructure} dependency breaks the build outright.
     */
    @Test
    void usecase_does_not_depend_on_infrastructure() {
        noClasses()
                .that().resideInAPackage("..usecase..")
                .should().dependOnClassesThat().resideInAPackage("..infrastructure..")
                .as("usecase must not depend on infrastructure..")
                .check(productionClasses);
    }

    /**
     * FROZEN (V1 — the optional DoD Refinement, deliberately deferred): interactors still construct
     * adapter DTOs/presenters. The current violations are recorded in {@code archunit_store/}; a new
     * {@code usecase -> adapter} dependency outside the frozen set breaks the build. Make this rule
     * strict (drop the {@code freeze}) once V1 is actually cleaned.
     */
    @Test
    void usecase_does_not_depend_on_adapter() {
        freeze(
                noClasses()
                        .that().resideInAPackage("..usecase..")
                        .should().dependOnClassesThat().resideInAPackage("..adapter..")
                        .as("usecase must not depend on adapter..")
        ).check(productionClasses);
    }

    /**
     * STRICT (V3): cross-module gateways in {@code workorder} must talk to the
     * public gateways of the other modules, never their Panache repositories / infrastructure.
     * No freeze — any new reach into another module's infrastructure breaks the build outright.
     */
    @Test
    void workorder_gateways_do_not_reach_other_modules_infrastructure() {
        noClasses()
                .that().resideInAPackage("..workorder.adapter.gateway..")
                .should().dependOnClassesThat().resideInAnyPackage(
                        "..customer.infrastructure..",
                        "..vehicle.infrastructure..",
                        "..autoservice.infrastructure..",
                        "..inventory.infrastructure..")
                .as("workorder gateways must depend on other modules' public gateways, not their infrastructure")
                .check(productionClasses);
    }
}
